<div class="<?php echo $this->getContainerClassString() ?>">
    <div class="buyersGuide-filter">
        <h2><?php echo print_r($this->getActionState(), true); ?></h2>
        <?php echo $this->getChildHtml('buyersguide_toolbar_supplemental') ?>
        <?php echo $this->getChildHtml('car_filter') ?>

        <div class="buyersGuide-filterInner last">
            <div class="buyersGuideCTA">
                <input type="button" class="go" id="buyersGuideStartButton" value="Go!"/>
            </div>
        </div>

        <input type="hidden" id="buyersGuideStartUrl" value="<?php echo $this->getUrl('*/*/*') ?>"/>

        <?php echo $this->getChildHtml('buyersguide_steps') ?>
    </div>
</div>