<div class="tile80">
    <span class="product-spec"><span class="weightBold-styleNormal">Overall:</span></span>
    <span class="product-spec">More efficient, longer lasting. Industry Standard in all vehicles that come factory-equipped with HID headlights. Best for use on vehicles with Canbus systems or weaker than average electrical systems (old vehicles, motorcycles, etc).</span>
</div>
<div class="tile80">
    <div class="tile-info">
        <a href="javascript:lightbox(null, '../buyersGuide/buyersGuide-ballasts_lightbox-info.html');">
            <span class="product-spec-icon">
                <img src="<?php echo $this->getSkinUrl('images/icon_info.svg') ?>" alt="What is this?" border="0" />
            </span>
        </a>
    </div>
    <div class="tile80">
        <span class="product-spec" style="margin-top:10px;">
            <span class="weightBold-styleNormal">Lumens:</span>
            <span class="weightRegular-styleItalic">5800-6200</span>
        </span>
        <span class="product-spec">
            <span class="weightBold-styleNormal">Lifespan:</span>
            <span class="weightRegular-styleItalic">~2,000 hrs</span>
        </span>
        <span class="product-spec">
            <span class="weightBold-styleNormal">Power Consumption:</span>
            <span class="weightRegular-styleItalic">average</span>
        </span>
        <span class="product-spec">
            <span class="weightBold-styleNormal">Color Shift:</span>
            <span class="weightRegular-styleItalic">none</span>
        </span>
    </div>
</div>



<div class="lightboxContainer">
    <div class="lightboxContent">
        <div class="lightboxHeadline"><h3>Terminology:</h3></div>
        <div class="navBtn-close">
            <a href="javascript:closeLightbox();">
                <img src="<?php echo $this->getSkinUrl('images/icon_menux2x.png') ?>" alt="Close" border="0"/>
            </a>
        </div>

        <div class="section">
	    	<span class="product-spec">
                <span class="weightBold-styleNormal white">Lumens:</span> <span class="weightRegular-styleItalic">This figure is given an an estimate for both headlights, and will depend on the bulbs used.</span>
            </span>
            <span class="product-spec">
                <span class="weightBold-styleNormal white">Lifespan:</span> <span class="weightRegular-styleItalic">On average; 2000 hours is approximately 7-10 years of normal driving. Since 50W ballasts run a bit hotter, their rated lifespan is 25% less than 35W, at 1500 hours. </span>
            </span>
            <span class="product-spec">
                <span class="weightBold-styleNormal white">Power Consumption:</span> <span class="weightRegular-styleItalic">When first igniting the bulbs, the ballasts consume more power than their steady state. XB35 ballasts require just above 4 Amps to turn on. XB55 ballasts require 1.5 Amps more.</span>
            </span>
            <span class="product-spec">
                <span class="weightBold-styleNormal white">Color Shift:</span> <span class="weightRegular-styleItalic">35W ballasts will drive the bulbs at their rated color/Kelvin rating. 50W ballasts will make the bulbs run brighter, but will decrease their Kelvin by approximately 1000K. (i.e. a 6000K bulb will look like a 5000K when powered by a 50W ballast, but will still be brighter)</span>
            </span>
        </div>
    </div>
</div>