<div class="tile80">
    <span class="product-spec"><span class="weightBold-styleNormal">Overall:</span></span>
    <span class="product-spec">More efficient, longer lasting. Industry Standard in all vehicles that come factory-equipped with HID headlights. Best for use on vehicles with Canbus systems or weaker than average electrical systems (old vehicles, motorcycles, etc).</span>
</div>
<div class="tile80">
    <div class="tile-info">
        <a href="javascript:lightbox(null, '../buyersGuide/buyersGuide-ballasts_lightbox-info.html');">
            <span class="product-spec-icon">
                <img src="<?php echo $this->getSkinUrl('images/icon_info.svg') ?>" alt="What is this?" border="0" />
            </span>
        </a>
    </div>
    <div class="tile80">
        <span class="product-spec" style="margin-top:10px;">
            <span class="weightBold-styleNormal">Lumens:</span>
            <span class="weightRegular-styleItalic">5800-6200</span>
        </span>
        <span class="product-spec">
            <span class="weightBold-styleNormal">Lifespan:</span>
            <span class="weightRegular-styleItalic">~2,000 hrs</span>
        </span>
        <span class="product-spec">
            <span class="weightBold-styleNormal">Power Consumption:</span>
            <span class="weightRegular-styleItalic">average</span>
        </span>
        <span class="product-spec">
            <span class="weightBold-styleNormal">Color Shift:</span>
            <span class="weightRegular-styleItalic">none</span>
        </span>
    </div>
</div>