<div class="tile80">
    <span class="product-spec"><span class="weightBold-styleNormal">Overall:</span></span>
    <span class="product-spec">Brighter, more power hungry, lesser lifepsan.  Produces more output compared to all factory-installed HID headlight ballasts. Not recommended without the use of a relayed wire harness or in smaller projector/housings (such as fog lights).</span>
</div>
<div class="tile80">
    <div class="tile-info">
        <a href="#wattageInfo" class="wattageInfoButton">
            <span class="product-spec-icon">
                <img src="<?php echo $this->getSkinUrl('images/icon_info.svg') ?>" alt="What is this?" border="0" />
            </span>
        </a>
    </div>
    <div class="tile80">
        <span class="product-spec" style="margin-top:10px;">
            <span class="weightBold-styleNormal">Lumens:</span>
            <span class="weightRegular-styleItalic">9100-9700</span>
        </span>
        <span class="product-spec">
            <span class="weightBold-styleNormal">Lifespan:</span>
            <span class="weightRegular-styleItalic">~1,500 hrs</span>
        </span>
        <span class="product-spec">
            <span class="weightBold-styleNormal">Power Consumption:</span>
            <span class="weightRegular-styleItalic">above average</span>
        </span>
        <span class="product-spec">
            <span class="weightBold-styleNormal">Color Shift:</span>
            <span class="weightRegular-styleItalic">yes</span>
        </span>
    </div>
</div>