<div class="buyersGuide-selections">
    <h2>We&apos;ve got a few more questions before we can find the right projector for you...</h2>
</div>
<div class="buyersGuide-select">
    <span class="productDrop-headline"><?php echo $this->getQuestion() ?></span>
    <div class="buyersGuide-selectWrap">
        <div class="selectWrap full">
            <?php foreach ($this->getOptions() as $idx => $option): ?>
                <div class="selectWrap-column tile">
                    <h3>
                        <?php echo $option->getTitle() ?>
                        <?php if ($option->getSubtitle()): ?>
                            <span class="weightRegular-styleNormal"><?php echo $option->getSubtitle() ?></span>
                        <?php endif; ?>
                    </h3>
                    <div class="tile-select" data-value="<?php echo $option->getId() ?>">&nbsp;</div>
                    <div class="tile80">
                        <span class="product-spec"><?php echo $option->getDesc() ?></span>
                        <?php if ($option->getPs()): ?>
                            <span class="product-spec">
                                <span class="weightRegular-styleItalic"><?php echo $option->getPs() ?></span>
                            </span>
                        <?php endif; ?>
                    </div>
                    <div class="tile-image">
                        <?php echo $option->getImage()->render() ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>