<div class="buyersGuide-selections">
    <h2>We&apos;ve got a few more questions before we can find the right projector for you...</h2>
</div>
<div class="buyersGuide-select">
    <span class="productDrop-headline"><?php echo $this->getQuestion() ?></span>
    <div class="buyersGuide-selectWrap">
        <div class="selectWrap full">
            <?php $useLastClass = true; ?>
            <?php foreach ($this->getOptions() as $idx => $option): ?>
                <?php $useLastClass = !$useLastClass; ?>
                <div class="selectWrap-column tile <?php if ($useLastClass) { echo "last"; } ?>">
                    <h3>
                        <?php echo $option->getTitle() ?>
                        <?php if ($option->getSubtitle()): ?>
                            <span class="weightRegular-styleNormal"><?php echo $option->getSubtitle() ?></span>
                        <?php endif; ?>
                    </h3>
                    <div class="tile-select" data-id="<?php echo $option->getId() ?>" data-value="<?php echo $option->getValue() ?>" data-displayValue="<?php echo $option->getDisplayValue() ?>">&nbsp;</div>
                    <div class="tile80">
                        <span class="product-spec"><?php echo $option->getDesc() ?></span>
                        <?php if ($option->getPs()): ?>
                            <span class="product-spec">
                                <span class="weightRegular-styleItalic"><?php echo $option->getPs() ?></span>
                            </span>
                        <?php endif; ?>
                    </div>
                    <?php
                    if ($option->getInfoTemplate()) {
                        echo $this->getLayout()
                            ->createBlock('core/template')
                            ->setTemplate($option->getInfoTemplate())
                            ->toHtml();
                    }
                    ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>