<div class="buyersGuide-questionMask">
    <div class="buyersGuide-questionWrap">

        <!-- error slide -->
        <div class="buyersGuide-questions qerror invisible" data-stepId="step_error">
            <div class="buyersGuide-selections">
                <h2>&nbsp;</h2>
            </div>
            <div class="buyersGuide-select">
                <h2>Oh no, there was an error!</h2>
            </div>
        </div>

        <!-- slide 0 aka the loading slide -->
        <div class="buyersGuide-questions qloading" data-stepId="step_loading">
            <div class="buyersGuide-selections">
                <h2>&nbsp;</h2>
            </div>
            <div class="buyersGuide-select" style="text-align: center;">
                <img src="<?php echo $this->getSkinUrl('images/carousel/ajax-loader.gif') ?>" style="background: white; padding: 1px; border-radius: 15px;"/>
            </div>
        </div>

        <div class="buyersGuide-questions qdone" data-stepId="step_done">
            <div class="buyersGuide-selections">
                <h2>&nbsp;</h2>
            </div>
            <div class="buyersGuide-select">
                <span class="productDrop-headline">That&apos;s it!  Check out the compatible products below.</span>
                <h2>
                    <span class="note">NOTE: We recommend consulting your owner&apos;s manual or <a href="<?php echo Mage::getUrl('contacts') ?>">contacting us</a> to verify fitment for your vehicle.  The recommendation below is based on the most accurate information we have about your application, but we are not responsible for misinformation.  Modification may be necessary for installation.</span>
                </h2>
            </div>
        </div>

        <div class="buyersGuide-questions qdirectfit" data-stepId="step_directfit">
            <div class="buyersGuide-select">
                <span class="productDrop-headline">That&apos;s it!  Check out the compatible products below.</span>
            </div>
        </div>

        <div class="buyersGuide-questions qnofit" data-stepId="step_nofit">
            <div class="buyersGuide-select">
                <span class="productDrop-headline">You just blew our computer's mind, but that doesn't mean we've got nothing for you!  Please <a href="<?php echo Mage::getUrl('contacts') ?>">contact us</a> for a human recommendation.</span>
            </div>
        </div>

        <div class="buyersGuide-questions qcontactus" data-stepId="step_contactus">
            <div class="buyersGuide-selections">
                <h2>&nbsp;</h2>
            </div>
            <div class="buyersGuide-select">
                <span class="productDrop-headline">This is a tricky one!  Please <a href="<?php echo Mage::getUrl('contacts') ?>">contact us</a> for more ideas.</span>
            </div>
        </div>

        <?php foreach ($this->getSteps() as $step): ?>
            <div class="buyersGuide-questions q<?php echo($step->getQ() ?: '1'); ?>" data-stepId="<?php echo $step->getStepId() ?>" data-stepDisplayName="<?php echo $step->getDisplayName() ?>">
                <?php echo $step->toHtml() ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>
