<div class="buyersGuide-questionMask">
    <div class="buyersGuide-questionWrap">

        <!-- error slide -->
        <div class="buyersGuide-questions qerror invisible" data-stepId="step_error">
            <div class="buyersGuide-selections">
                <h2>This is the selections container.</h2>
            </div>
            <div class="buyersGuide-select">
                <h2>Oh no, there was an error!</h2>
            </div>
        </div>

        <!-- slide 0 aka the loading slide -->
        <div class="buyersGuide-questions qloading" data-stepId="step_loading">
            <div class="buyersGuide-selections">
                <h2>This is the selections container.</h2>
            </div>
            <div class="buyersGuide-select" style="text-align: center;">
                <img src="<?php echo $this->getSkinUrl('images/carousel/ajax-loader.gif') ?>" style="background: white; padding: 1px; border-radius: 15px;"/>
            </div>
        </div>

        <div class="buyersGuide-questions qdone" data-stepId="step_done">
            <div class="buyersGuide-selections">
                <h2>This is the selections container.</h2>
            </div>
            <div class="buyersGuide-select">
                <span class="productDrop-headline">Finished! Check out our product recommendation below.</span>
                <h2>
                    <span class="note">NOTE: This is a retrofit product - modifications may need to be required for installation.</span>
                </h2>
            </div>
        </div>

        <div class="buyersGuide-questions qdirectfit" data-stepId="step_directfit">
            <div class="buyersGuide-select">
                <span class="productDrop-headline">That&apos;s it!  Check out the direct-fit product solutions below.</span>
            </div>
        </div>

        <div class="buyersGuide-questions qnofit" data-stepId="step_nofit">
            <div class="buyersGuide-select">
                <span class="productDrop-headline">Unfortunately we do not carry a product solution for this vehicle.</span>
            </div>
        </div>

        <?php foreach ($this->getSteps() as $step): ?>
            <div class="buyersGuide-questions q<?php echo($step->getQ() ?: '1'); ?>" data-stepId="<?php echo $step->getStepId() ?>" data-stepDisplayName="<?php echo $step->getDisplayName() ?>">
                <?php echo $step->toHtml() ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>
