<div class="buyersGuide-selections">
    <h2>We&apos;ve got a few more questions before we can find the right projector for you...</h2>
</div>
<div class="buyersGuide-select">
    <span class="productDrop-headline"><?php echo $this->getQuestion() ?></span>
    <div class="buyersGuide-selectWrap">
        <div class="selectWrap-full">
            <div class="selectWrap-column">
                <?php if ($this->getImage()) {
                    echo($this->getImage()->render());
                } ?>
            </div>
            <div class="selectWrap-column last">
                <?php foreach ($this->getOptions() as $idx => $option): ?>
                    <div class="tile">
                        <h3 class="tile30"><?php echo $option->getTitle() ?></h3>
                        <div class="tile50">
                            <?php foreach (explode("\n", trim($option->getDesc())) as $descriptor): ?>
                                <span class="product-spec"><?php echo trim($descriptor) ?></span>
                            <?php endforeach; ?>
                        </div>
                        <div class="tile-select" data-value="<?php echo $option->getId() ?>">&nbsp;</div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>