<div class="buyersGuide-selections">
    <h2>We&apos;ve got a few more questions before we can find the right projector for you...</h2>
</div>
<div class="buyersGuide-select">
    <span class="productDrop-headline"><?php echo $this->getQuestion() ?></span>
    <?php if ($this->getStepDesc()): ?>
        <span class="product-spec"><?php echo $this->getStepDesc() ?></span>
    <?php endif; ?>
    <div class="buyersGuide-selectWrap">
        <div class="selectWrap-ext-fade">
            <img src="<?php echo $this->getSkinUrl('images/productcategory/selectWrap-ext-fade.png') ?>" alt="Scroll Fade" border="0">
        </div>
        <div class="selectWrap-ext">
            <?php foreach ($this->getOptions() as $idx => $option): ?>
                <div class="selectWrap-column tile">
                    <h3><?php echo $option->getTitle() ?></h3>
                    <div class="tile-select" data-id="<?php echo $option->getId() ?>" data-value="<?php echo $option->getValue() ?>" data-displayValue="<?php echo $option->getDisplayValue() ?>">&nbsp;</div>
                    <div class="tile-image">
                        <?php if ($option->getImage()) {
                            echo ($option->getImage()->render());
                        } ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>