<div class="buyersGuide-selections">
    <h2>We&apos;ve got a few more questions before we can find the right projector for you...</h2>
</div>
<div class="buyersGuide-select">
    <span class="productDrop-headline"><?php echo $this->getQuestion() ?></span>
    <?php if ($this->getStepDesc()): ?>
        <span class="product-spec"><?php echo $this->getStepDesc() ?></span>
    <?php endif; ?>
    <div class="buyersGuide-selectWrap">
        <div class="selectWrap-ext-fade">
            <img src="<?php echo $this->getSkinUrl('images/productcategory/selectWrap-ext-fade.png') ?>" alt="Scroll Fade" border="0">
        </div>
        <div class="selectWrap-ext">
            <?php foreach ($this->getOptions() as $idx => $option): ?>
                <div class="selectWrap-column tile">
                    <h3>
                        <?php echo $option->getTitle() ?>
                        <?php if ($option->getSubtitle()) { echo(" <span class='weightRegular-styleNormal'>{$option->getSubtitle()}</span>"); } ?>
                    </h3>
                    <div class="tile-select" data-id="<?php echo $option->getId() ?>" data-groupId="<?php echo $option->getGroupId() ?>" data-value="<?php echo $option->getValue() ?>" data-displayValue="<?php echo $option->getDisplayValue() ?>">&nbsp;</div>

                    <?php
                    $_ps = $option->getPs();
                    $_desc = $option->getDesc();
                    if ($_desc || $_ps):
                        ?>
                        <div class="tile80">
                            <?php if ($_desc) { echo("<span class='product-spec'>$_desc</span>"); } ?>
                            <?php if($_ps): ?>
                                <span class="product-spec">
                                    <span class="weightRegular-styleItalic"><?php echo $_ps ?></span>
                                </span>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>
                    <div class="tile-image">
                        <?php if ($option->getImage()) {
                            echo ($option->getImage()->render());
                        } ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>